Repository PattaFeuFeu/bigbone, pull requests merged in 2023-10, with the labels that each got.

#267 Update SearchContent with all possible request params
  bigbone-rx/src/main/kotlin/social/bigbone/rx/RxSearchMethods.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/SearchMethods.kt
  bigbone/src/test/assets/search_for_statuses_ranging_ids.json
  bigbone/src/test/assets/search_only_accounts.json
  bigbone/src/test/kotlin/social/bigbone/api/method/SearchMethodsTest.kt
Labels: hacktoberfest-accepted

#275 Add dependabot for GitHub Actions workflow dependencies
  .github/dependabot.yml
Labels: hacktoberfest-accepted

#268 Update API calling favourites related dto
  bigbone/src/main/kotlin/social/bigbone/api/Link.kt
  bigbone/src/main/kotlin/social/bigbone/api/Pageable.kt
  bigbone/src/main/kotlin/social/bigbone/api/Range.kt
  bigbone/src/main/kotlin/social/bigbone/api/entity/PreviewCard.kt
  bigbone/src/main/kotlin/social/bigbone/api/entity/Status.kt
  bigbone/src/main/kotlin/social/bigbone/api/entity/Tag.kt
  bigbone/src/main/kotlin/social/bigbone/api/entity/data/History.kt
  bigbone/src/test/kotlin/social/bigbone/api/RangeTest.kt
Labels: hacktoberfest-accepted

#271 Add missing report field to Notification entity
  bigbone/src/main/kotlin/social/bigbone/api/entity/Notification.kt
  bigbone/src/main/kotlin/social/bigbone/api/entity/Report.kt
  bigbone/src/test/assets/notifications.json
  bigbone/src/test/kotlin/social/bigbone/api/method/NotificationMethodsTest.kt
Labels: hacktoberfest-accepted

#277 Update ReportMethods by adding all request params
  bigbone-rx/src/main/kotlin/social/bigbone/rx/RxReportMethods.kt
  bigbone/src/main/kotlin/social/bigbone/api/entity/Report.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/ReportMethods.kt
  bigbone/src/test/assets/reports.json
  bigbone/src/test/kotlin/social/bigbone/api/method/ReportMethodsTest.kt
Labels: breaking, hacktoberfest-accepted

#285 Remove explicitly set kotlin-stdlib from Gradle scripts
  bigbone-rx/build.gradle
  bigbone/build.gradle
  gradle/libs.versions.toml
Labels: code quality, hacktoberfest-accepted

#290 Return instance version from server info if available
  bigbone/src/main/kotlin/social/bigbone/MastodonClient.kt
Labels: hacktoberfest-accepted

#281 Add ktlint plugin code styling and formatting
  bigbone-rx/build.gradle
  bigbone-rx/src/main/kotlin/social/bigbone/rx/RxAccountMethods.kt
  bigbone/build.gradle
  bigbone/src/integrationTest/kotlin/social/bigbone/v300/V300TestSuite.kt
  bigbone/src/integrationTest/kotlin/social/bigbone/v402/V402TestSuite.kt
  bigbone/src/integrationTest/kotlin/social/bigbone/v410/V410StatusMethodsIntegrationTest.kt
  bigbone/src/integrationTest/kotlin/social/bigbone/v410/V410TestSuite.kt
  bigbone/src/main/kotlin/social/bigbone/JsonSerializer.kt
  bigbone/src/main/kotlin/social/bigbone/MastodonClient.kt
  bigbone/src/main/kotlin/social/bigbone/api/Range.kt
  bigbone/src/main/kotlin/social/bigbone/api/entity/Conversation.kt
  bigbone/src/main/kotlin/social/bigbone/api/entity/Filter.kt
  bigbone/src/main/kotlin/social/bigbone/api/entity/Marker.kt
  bigbone/src/main/kotlin/social/bigbone/api/entity/MastodonList.kt
  bigbone/src/main/kotlin/social/bigbone/api/entity/MediaAttachment.kt
  bigbone/src/main/kotlin/social/bigbone/api/entity/PreviewCard.kt
  bigbone/src/main/kotlin/social/bigbone/api/entity/Report.kt
  bigbone/src/main/kotlin/social/bigbone/api/entity/StatusEdit.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/AccountMethods.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/FeaturedTagsMethods.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/MarkerMethods.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/ReportMethods.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/SearchMethods.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/StatusMethods.kt
  bigbone/src/main/kotlin/social/bigbone/nodeinfo/NodeInfoClient.kt
  bigbone/src/test/kotlin/social/bigbone/api/method/FeaturedTagsMethodsTest.kt
  bigbone/src/test/kotlin/social/bigbone/api/method/MarkerMethodsTest.kt
  bigbone/src/test/kotlin/social/bigbone/api/method/StatusMethodsTest.kt
  buildSrc/src/main/groovy/bigbone.kotlin-conventions.gradle
  config/detekt/detekt.yml
  gradle/libs.versions.toml
  sample-kotlin/build.gradle
  sample-kotlin/src/main/kotlin/social/bigbone/sample/GetHomeTimelineWithFiltering.kt
Labels: code quality, pipeline, hacktoberfest-accepted

#286 Implement endorsements API
  bigbone-rx/src/main/kotlin/social/bigbone/rx/RxEndorsementMethods.kt
  bigbone-rx/src/test/assets/endorsements_view_success.json
  bigbone-rx/src/test/kotlin/social/bigbone/rx/RxEndorsementMethodsTest.kt
  bigbone-rx/src/test/kotlin/social/bigbone/rx/testtool/MockClient.kt
  bigbone/src/main/kotlin/social/bigbone/MastodonClient.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/EndorsementMethods.kt
  bigbone/src/test/assets/endorsements_view_success.json
  bigbone/src/test/kotlin/social/bigbone/api/method/EndorsementMethodsTest.kt
  bigbone/src/test/kotlin/social/bigbone/testtool/MockClient.kt
Labels: enhancement, hacktoberfest-accepted

#287 Add domain_blocks API
  bigbone-rx/src/main/kotlin/social/bigbone/rx/RxDomainBlocksMethods.kt
  bigbone-rx/src/test/assets/domain_blocks_block_error_422.json
  bigbone-rx/src/test/assets/domain_blocks_block_success.json
  bigbone-rx/src/test/assets/domain_blocks_view_success.json
  bigbone-rx/src/test/assets/error_401_unauthorized.json
  bigbone-rx/src/test/kotlin/social/bigbone/rx/RxDomainBlocksMethodsTest.kt
  bigbone-rx/src/test/kotlin/social/bigbone/rx/testtool/MockClient.kt
  bigbone/src/main/kotlin/social/bigbone/MastodonClient.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/DomainBlocksMethods.kt
  bigbone/src/test/assets/domain_blocks_block_error_422.json
  bigbone/src/test/assets/domain_blocks_block_success.json
  bigbone/src/test/assets/domain_blocks_unblock_error_422.json
  bigbone/src/test/assets/domain_blocks_unblock_success.json
  bigbone/src/test/assets/domain_blocks_view_success.json
  bigbone/src/test/kotlin/social/bigbone/api/method/DomainBlocksMethodsTest.kt
  bigbone/src/test/kotlin/social/bigbone/testtool/MockClient.kt
Labels: enhancement, hacktoberfest-accepted

#301 Add custom_emojis API methods
  bigbone-rx/src/main/kotlin/social/bigbone/rx/RxCustomEmojisMethods.kt
  bigbone/src/main/kotlin/social/bigbone/MastodonClient.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/CustomEmojisMethods.kt
  bigbone/src/test/assets/custom_emojis_success.json
  bigbone/src/test/kotlin/social/bigbone/api/method/CustomEmojisMethodsTest.kt
Labels: enhancement, hacktoberfest-accepted

#302 Implement dismiss single notification request
  bigbone-rx/src/main/kotlin/social/bigbone/rx/RxNotificationMethods.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/NotificationMethods.kt
  bigbone/src/test/assets/notifications_dismiss_success.json
  bigbone/src/test/kotlin/social/bigbone/api/method/NotificationMethodsTest.kt
  bigbone/src/test/kotlin/social/bigbone/testtool/MockClient.kt
Labels: enhancement, breaking, hacktoberfest-accepted

#291 Feat Suggestion methods api
  bigbone-rx/src/main/kotlin/social/bigbone/rx/RxSuggestionMethods.kt
  bigbone/src/main/kotlin/social/bigbone/MastodonClient.kt
  bigbone/src/main/kotlin/social/bigbone/api/entity/Suggestion.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/SuggestionMethods.kt
  bigbone/src/test/assets/suggestions.json
  bigbone/src/test/kotlin/social/bigbone/api/method/SuggestionMethodsTest.kt
Labels: enhancement, hacktoberfest-accepted

#284 implement preferences API methods
  bigbone-rx/src/main/kotlin/social/bigbone/rx/RxPreferenceMethods.kt
  bigbone-rx/src/main/kotlin/social/bigbone/rx/RxStatusMethods.kt
  bigbone/src/integrationTest/kotlin/social/bigbone/v410/V410StatusMethodsIntegrationTest.kt
  bigbone/src/main/kotlin/social/bigbone/MastodonClient.kt
  bigbone/src/main/kotlin/social/bigbone/api/entity/Preferences.kt
  bigbone/src/main/kotlin/social/bigbone/api/entity/ScheduledStatus.kt
  bigbone/src/main/kotlin/social/bigbone/api/entity/Status.kt
  bigbone/src/main/kotlin/social/bigbone/api/entity/data/Visibility.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/PreferenceMethods.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/StatusMethods.kt
  bigbone/src/test/assets/preferences.json
  bigbone/src/test/kotlin/social/bigbone/api/entity/StatusTest.kt
  bigbone/src/test/kotlin/social/bigbone/api/method/PreferenceMethodsTest.kt
  bigbone/src/test/kotlin/social/bigbone/api/method/StatusMethodsTest.kt
  sample-java/src/main/java/social/bigbone/sample/PostStatusWithMediaAttached.java
  sample-kotlin/src/main/kotlin/social/bigbone/sample/PostStatusWithMediaAttached.kt
Labels: enhancement, hacktoberfest-accepted

#288 Replace Single/Completable#create with fromCallable/fromAction
  README.md
  bigbone-rx/README.md
  bigbone-rx/src/main/kotlin/social/bigbone/rx/RxAccountMethods.kt
  bigbone-rx/src/main/kotlin/social/bigbone/rx/RxAppMethods.kt
  bigbone-rx/src/main/kotlin/social/bigbone/rx/RxBlockMethods.kt
  bigbone-rx/src/main/kotlin/social/bigbone/rx/RxBookmarkMethods.kt
  bigbone-rx/src/main/kotlin/social/bigbone/rx/RxConversationMethods.kt
  bigbone-rx/src/main/kotlin/social/bigbone/rx/RxDirectoryMethods.kt
  bigbone-rx/src/main/kotlin/social/bigbone/rx/RxEndorsementMethods.kt
  bigbone-rx/src/main/kotlin/social/bigbone/rx/RxFavouriteMethods.kt
  bigbone-rx/src/main/kotlin/social/bigbone/rx/RxFeaturedTagsMethods.kt
  bigbone-rx/src/main/kotlin/social/bigbone/rx/RxFilterMethods.kt
  bigbone-rx/src/main/kotlin/social/bigbone/rx/RxFollowRequestMethods.kt
  bigbone-rx/src/main/kotlin/social/bigbone/rx/RxInstanceMethods.kt
  bigbone-rx/src/main/kotlin/social/bigbone/rx/RxListMethods.kt
  bigbone-rx/src/main/kotlin/social/bigbone/rx/RxMarkerMethods.kt
  bigbone-rx/src/main/kotlin/social/bigbone/rx/RxMediaMethods.kt
  bigbone-rx/src/main/kotlin/social/bigbone/rx/RxMuteMethods.kt
  bigbone-rx/src/main/kotlin/social/bigbone/rx/RxNotificationMethods.kt
  bigbone-rx/src/main/kotlin/social/bigbone/rx/RxOAuthMethods.kt
  bigbone-rx/src/main/kotlin/social/bigbone/rx/RxPollMethods.kt
  bigbone-rx/src/main/kotlin/social/bigbone/rx/RxReportMethods.kt
  bigbone-rx/src/main/kotlin/social/bigbone/rx/RxSearchMethods.kt
  bigbone-rx/src/main/kotlin/social/bigbone/rx/RxStatusMethods.kt
  bigbone-rx/src/main/kotlin/social/bigbone/rx/RxSuggestionMethods.kt
  bigbone-rx/src/main/kotlin/social/bigbone/rx/RxTagMethods.kt
  bigbone-rx/src/main/kotlin/social/bigbone/rx/RxTimelineMethods.kt
  bigbone-rx/src/main/kotlin/social/bigbone/rx/extensions/CompletableExtensions.kt
  bigbone-rx/src/main/kotlin/social/bigbone/rx/extensions/GlobalFunctions.kt
  bigbone-rx/src/main/kotlin/social/bigbone/rx/extensions/SingleExtensions.kt
Labels: code quality, breaking, hacktoberfest-accepted

#306 Updated contributing file with project structure
  CONTRIBUTING.md
Labels: hacktoberfest-accepted

#303 Implement instance API methods
  bigbone-rx/src/main/kotlin/social/bigbone/rx/RxInstanceMethods.kt
  bigbone/src/main/kotlin/social/bigbone/api/entity/Instance.kt
  bigbone/src/main/kotlin/social/bigbone/api/entity/InstanceV1.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/InstanceMethods.kt
  bigbone/src/test/assets/instance.json
  bigbone/src/test/assets/instance_activity_success.json
  bigbone/src/test/assets/instance_domain_blocks_success.json
  bigbone/src/test/assets/instance_extended.json
  bigbone/src/test/assets/instance_extended_description_success.json
  bigbone/src/test/assets/instance_peers_success.json
  bigbone/src/test/assets/instance_rules_success.json
  bigbone/src/test/assets/instance_v1_extended.json
  bigbone/src/test/kotlin/social/bigbone/api/method/InstanceMethodsTest.kt
Labels: enhancement, breaking, hacktoberfest-accepted

#312 Parse ISO 8601 date(time) strings as Instant
  bigbone-rx/src/main/kotlin/social/bigbone/rx/RxStatusMethods.kt
  bigbone/src/integrationTest/kotlin/social/bigbone/TestHelpers.kt
  bigbone/src/integrationTest/kotlin/social/bigbone/v410/V410StatusMethodsIntegrationTest.kt
  bigbone/src/main/kotlin/social/bigbone/JsonSerializer.kt
  bigbone/src/main/kotlin/social/bigbone/PrecisionDateTime.kt
  bigbone/src/main/kotlin/social/bigbone/api/entity/Account.kt
  bigbone/src/main/kotlin/social/bigbone/api/entity/FeaturedTag.kt
  bigbone/src/main/kotlin/social/bigbone/api/entity/Filter.kt
  bigbone/src/main/kotlin/social/bigbone/api/entity/Instance.kt
  bigbone/src/main/kotlin/social/bigbone/api/entity/Marker.kt
  bigbone/src/main/kotlin/social/bigbone/api/entity/Notification.kt
  bigbone/src/main/kotlin/social/bigbone/api/entity/Poll.kt
  bigbone/src/main/kotlin/social/bigbone/api/entity/Report.kt
  bigbone/src/main/kotlin/social/bigbone/api/entity/ScheduledStatus.kt
  bigbone/src/main/kotlin/social/bigbone/api/entity/Status.kt
  bigbone/src/main/kotlin/social/bigbone/api/entity/StatusEdit.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/StatusMethods.kt
  bigbone/src/test/assets/notifications.json
  bigbone/src/test/java/social/bigbone/DateTimeSerializerJavaTest.java
  bigbone/src/test/kotlin/social/bigbone/DateTimeSerializerTest.kt
  bigbone/src/test/kotlin/social/bigbone/api/entity/StatusTest.kt
  bigbone/src/test/kotlin/social/bigbone/api/method/EndorsementMethodsTest.kt
  bigbone/src/test/kotlin/social/bigbone/api/method/FeaturedTagMethodsTest.kt
  bigbone/src/test/kotlin/social/bigbone/api/method/InstanceMethodsTest.kt
  bigbone/src/test/kotlin/social/bigbone/api/method/MarkerMethodsTest.kt
  bigbone/src/test/kotlin/social/bigbone/api/method/NotificationMethodsTest.kt
  bigbone/src/test/kotlin/social/bigbone/api/method/ReportMethodsTest.kt
  bigbone/src/test/kotlin/social/bigbone/api/method/StatusMethodsTest.kt
  sample-java/src/main/java/social/bigbone/sample/GetDirectoryAccounts.java
  sample-kotlin/src/main/kotlin/social/bigbone/sample/GetDirectoryAccounts.kt
Labels: enhancement, breaking
