Repository PattaFeuFeu/bigbone, pull requests merged in 2023-11, with the labels that each got.

#309 Add Announcement API
  bigbone-rx/src/main/kotlin/social/bigbone/rx/RxAnnouncementMethods.kt
  bigbone/src/main/kotlin/social/bigbone/MastodonClient.kt
  bigbone/src/main/kotlin/social/bigbone/api/entity/Announcement.kt
  bigbone/src/main/kotlin/social/bigbone/api/entity/Reaction.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/AnnouncementMethods.kt
  bigbone/src/test/assets/announcement_dismiss_success.json
  bigbone/src/test/assets/announcements.json
  bigbone/src/test/assets/announcements_add_reaction_success.json
  bigbone/src/test/assets/announcements_remove_reaction_success.json
  bigbone/src/test/kotlin/social/bigbone/api/method/AnnouncementMethodsTest.kt
Labels: hacktoberfest-accepted

#319 PreviewCard property fixes
  bigbone/src/main/kotlin/social/bigbone/api/entity/PreviewCard.kt
  bigbone/src/test/assets/status_with_previewcard.json
  bigbone/src/test/kotlin/social/bigbone/api/method/StatusMethodsTest.kt
Labels: breaking

#317 #299 Implement oEmbed API methods
  bigbone-rx/src/main/kotlin/social/bigbone/rx/RxOEmbedMethods.kt
  bigbone/src/main/kotlin/social/bigbone/MastodonClient.kt
  bigbone/src/main/kotlin/social/bigbone/api/entity/OEmbedMetadata.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/OEmbedMethods.kt
  bigbone/src/test/assets/oembed_get_success.json
  bigbone/src/test/kotlin/social/bigbone/api/method/OEmbedMethodsTest.kt
  sample-java/src/main/java/social/bigbone/sample/GetOEmbedMetadata.java
  sample-kotlin/src/main/kotlin/social/bigbone/sample/GetOEmbedMetadata.kt
Labels: enhancement

#316 Feat new push notifications methods
  bigbone-rx/src/main/kotlin/social/bigbone/rx/RxPushNotificationMethods.kt
  bigbone/src/main/kotlin/social/bigbone/MastodonClient.kt
  bigbone/src/main/kotlin/social/bigbone/api/entity/WebPushSubscription.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/PushNotificationMethods.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/StatusMethods.kt
  bigbone/src/test/assets/push_notification_subscription.json
  bigbone/src/test/kotlin/social/bigbone/api/method/PushNotificationMethodsTest.kt
Labels: enhancement, hacktoberfest-accepted

#334 Add admin/retention methods
  bigbone-rx/src/main/kotlin/social/bigbone/rx/admin/RxAdminRetentionMethods.kt
  bigbone/src/main/kotlin/social/bigbone/JsonSerializer.kt
  bigbone/src/main/kotlin/social/bigbone/MastodonClient.kt
  bigbone/src/main/kotlin/social/bigbone/api/entity/admin/AdminCohort.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/admin/AdminRetentionMethods.kt
  bigbone/src/test/assets/admin_retention_calculate_retention_data_daily_success.json
  bigbone/src/test/assets/admin_retention_calculate_retention_data_monthly_success.json
  bigbone/src/test/kotlin/social/bigbone/api/method/admin/AdminRetentionMethodsTest.kt
Labels: enhancement

#333 Add admin/measures methods
  bigbone-rx/src/main/kotlin/social/bigbone/rx/admin/RxAdminMeasuresMethods.kt
  bigbone/src/main/kotlin/social/bigbone/MastodonClient.kt
  bigbone/src/main/kotlin/social/bigbone/api/entity/admin/AdminMeasure.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/admin/AdminMeasureMethods.kt
  bigbone/src/test/assets/admin_measures_get_measurable_data_success.json
  bigbone/src/test/assets/error_403_forbidden.json
  bigbone/src/test/kotlin/social/bigbone/api/method/admin/AdminMeasureMethodsTest.kt
Labels: enhancement

#332 Add missing types and parameters to Notifications API
  bigbone-rx/src/main/kotlin/social/bigbone/rx/RxNotificationMethods.kt
  bigbone/src/main/kotlin/social/bigbone/MastodonClient.kt
  bigbone/src/main/kotlin/social/bigbone/Parameters.kt
  bigbone/src/main/kotlin/social/bigbone/api/entity/Notification.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/NotificationMethods.kt
  bigbone/src/test/kotlin/social/bigbone/api/method/NotificationMethodsTest.kt
  bigbone/src/test/kotlin/social/bigbone/api/method/admin/AdminMeasureMethodsTest.kt
  sample-kotlin/src/main/kotlin/social/bigbone/sample/GetNotifications.kt
Labels: enhancement, code quality

#347 Move documentation into docs folder
  docs/.gitignore
  docs/CNAME
  docs/Gemfile
  docs/LICENSE
  docs/README.md
  docs/_config.yml
  docs/api-coverage/accounts.md
  docs/api-coverage/admin/accounts.md
  docs/api-coverage/admin/canonical-email-blocks.md
  docs/api-coverage/admin/dimensions.md
  docs/api-coverage/admin/domain-allows.md
  docs/api-coverage/admin/domain-blocks.md
  docs/api-coverage/admin/email-domain-blocks.md
  docs/api-coverage/admin/index.md
  docs/api-coverage/admin/ip-blocks.md
  docs/api-coverage/admin/measures.md
  docs/api-coverage/admin/reports.md
  docs/api-coverage/admin/retention.md
  docs/api-coverage/admin/trends.md
  docs/api-coverage/announcements.md
  docs/api-coverage/apps.md
  docs/api-coverage/blocks.md
  docs/api-coverage/bookmarks.md
  docs/api-coverage/conversations.md
  docs/api-coverage/custom-emojis.md
  docs/api-coverage/directory.md
  docs/api-coverage/domain-blocks.md
  docs/api-coverage/emails.md
  docs/api-coverage/endorsements.md
  docs/api-coverage/favourites.md
  docs/api-coverage/featured-tags.md
  docs/api-coverage/filters.md
  docs/api-coverage/follow-requests.md
  docs/api-coverage/followed-tags.md
  docs/api-coverage/index.md
  docs/api-coverage/instance.md
  docs/api-coverage/lists.md
  docs/api-coverage/markers.md
  docs/api-coverage/media.md
  docs/api-coverage/mutes.md
  docs/api-coverage/notifications.md
  docs/api-coverage/oauth.md
  docs/api-coverage/oembed.md
  docs/api-coverage/polls.md
  docs/api-coverage/preferences.md
  docs/api-coverage/push.md
  docs/api-coverage/reports.md
  docs/api-coverage/scheduled-statuses.md
  docs/api-coverage/search.md
  docs/api-coverage/statuses.md
  docs/api-coverage/streaming.md
  docs/api-coverage/suggestions.md
  docs/api-coverage/tags.md
  docs/api-coverage/timelines.md
  docs/api-coverage/trends.md
  docs/assets/green16.png
  docs/assets/orange16.png
  docs/assets/red16.png
  docs/getting-started.md
  docs/index.md
Labels: documentation

#354 Add emails methods
  bigbone-rx/src/main/kotlin/social/bigbone/rx/RxEmailMethods.kt
  bigbone/src/main/kotlin/social/bigbone/MastodonClient.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/EmailMethods.kt
  bigbone/src/test/assets/emails_resend_confirmation_mail_success.json
  bigbone/src/test/kotlin/social/bigbone/api/method/EmailMethodsTest.kt
  docs/api-coverage/emails.md
Labels: documentation, enhancement

#356 Update pull request template
  pull_request_template.md
Labels: documentation, code quality

#359 Update markdown documentation in the root folder of the project
  CONTRIBUTING.md
  README.md
  SUPPORT.md
Labels: documentation

#336 Add release script that reacts on tags like v2.0.0
  .github/workflows/release.yml
  buildSrc/src/main/groovy/bigbone.library-conventions.gradle
Labels: enhancement, pipeline, github_actions

#353 Propagate exceptions occurring during client instantiation
  USAGE.md
  bigbone/src/main/kotlin/social/bigbone/MastodonClient.kt
  bigbone/src/main/kotlin/social/bigbone/api/exception/BigBoneClientInstantiationException.kt
  bigbone/src/main/kotlin/social/bigbone/nodeinfo/NodeInfoClient.kt
  bigbone/src/test/assets/mastodon_client_v1_instance_response.json
  bigbone/src/test/assets/mastodon_client_v2_instance_response.json
  bigbone/src/test/kotlin/social/bigbone/MastodonClientTest.kt
  sample-java/src/main/java/social/bigbone/sample/Authenticator.java
  sample-java/src/main/java/social/bigbone/sample/GetAppRegistration.java
  sample-java/src/main/java/social/bigbone/sample/GetBookmarks.java
  sample-java/src/main/java/social/bigbone/sample/GetConversations.java
  sample-java/src/main/java/social/bigbone/sample/GetMarkers.java
  sample-java/src/main/java/social/bigbone/sample/GetPublicTimeline.java
  sample-java/src/main/java/social/bigbone/sample/GetRawJson.java
  sample-java/src/main/java/social/bigbone/sample/GetTagTimeline.java
  sample-java/src/main/java/social/bigbone/sample/ManageFilters.java
  sample-java/src/main/java/social/bigbone/sample/PerformSimpleSearch.java
  sample-java/src/main/java/social/bigbone/sample/PostStatusWithMediaAttached.java
Labels: bug
