Repository PattaFeuFeu/bigbone, pull requests merged in 2023-12, with the labels that each got.

#360 Implement Trends API
  bigbone-rx/src/main/kotlin/social/bigbone/rx/RxTrendMethods.kt
  bigbone/src/main/kotlin/social/bigbone/MastodonClient.kt
  bigbone/src/main/kotlin/social/bigbone/api/entity/TrendsLink.kt
  bigbone/src/main/kotlin/social/bigbone/api/entity/data/History.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/TrendMethods.kt
  bigbone/src/test/assets/trends_view_trending_links_success.json
  bigbone/src/test/assets/trends_view_trending_statuses_success.json
  bigbone/src/test/assets/trends_view_trending_tags_success.json
  bigbone/src/test/kotlin/social/bigbone/api/method/TrendMethodsTest.kt
  docs/api-coverage/trends.md
Labels: enhancement

#363 Create SECURITY.md
  README.md
  SECURITY.md
Labels: documentation, security

#369 Upgrade Gradle from 8.4 to 8.5
  gradle/wrapper/gradle-wrapper.properties
Labels: pipeline

#370 oAuth: Add missing function parameters, add revoke token method
  bigbone-rx/src/main/kotlin/social/bigbone/rx/RxOAuthMethods.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/OAuthMethods.kt
  bigbone/src/test/assets/oauth_revoke_token_success.json
  bigbone/src/test/kotlin/social/bigbone/api/method/OAuthMethodsTest.kt
  docs/api-coverage/oauth.md
  sample-java/src/main/java/social/bigbone/sample/OAuthGetAccessToken.java
  sample-kotlin/src/main/kotlin/social/bigbone/sample/OAuthGetAccessToken.kt
Labels: documentation, enhancement, breaking

#371 followRequests: Change return to Relationship
  bigbone-rx/src/main/kotlin/social/bigbone/rx/RxFollowRequestMethods.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/FollowRequestMethods.kt
  bigbone/src/test/assets/follow_requests_accept_follow_requests_success.json
  bigbone/src/test/assets/follow_requests_reject_follow_requests_success.json
  bigbone/src/test/kotlin/social/bigbone/api/method/FollowRequestMethodsTest.kt
  docs/api-coverage/follow-requests.md
Labels: documentation, enhancement, breaking

#374 RxAppMethods: Add missing `verifyCredentials`
  bigbone-rx/src/main/kotlin/social/bigbone/rx/RxAppMethods.kt
Labels: enhancement

#372 Add missing kDocs to all RxJava implementations
  bigbone-rx/src/main/kotlin/social/bigbone/rx/RxAccountMethods.kt
  bigbone-rx/src/main/kotlin/social/bigbone/rx/RxAnnouncementMethods.kt
  bigbone-rx/src/main/kotlin/social/bigbone/rx/RxAppMethods.kt
  bigbone-rx/src/main/kotlin/social/bigbone/rx/RxBlockMethods.kt
  bigbone-rx/src/main/kotlin/social/bigbone/rx/RxBookmarkMethods.kt
  bigbone-rx/src/main/kotlin/social/bigbone/rx/RxConversationMethods.kt
  bigbone-rx/src/main/kotlin/social/bigbone/rx/RxCustomEmojiMethods.kt
  bigbone-rx/src/main/kotlin/social/bigbone/rx/RxDirectoryMethods.kt
  bigbone-rx/src/main/kotlin/social/bigbone/rx/RxFavouriteMethods.kt
  bigbone-rx/src/main/kotlin/social/bigbone/rx/RxFilterMethods.kt
  bigbone-rx/src/main/kotlin/social/bigbone/rx/RxListMethods.kt
  bigbone-rx/src/main/kotlin/social/bigbone/rx/RxMarkerMethods.kt
  bigbone-rx/src/main/kotlin/social/bigbone/rx/RxMediaMethods.kt
  bigbone-rx/src/main/kotlin/social/bigbone/rx/RxMuteMethods.kt
  bigbone-rx/src/main/kotlin/social/bigbone/rx/RxNotificationMethods.kt
  bigbone-rx/src/main/kotlin/social/bigbone/rx/RxPollMethods.kt
  bigbone-rx/src/main/kotlin/social/bigbone/rx/RxReportMethods.kt
  bigbone-rx/src/main/kotlin/social/bigbone/rx/RxSearchMethods.kt
  bigbone-rx/src/main/kotlin/social/bigbone/rx/RxStatusMethods.kt
  bigbone-rx/src/main/kotlin/social/bigbone/rx/RxSuggestionMethods.kt
  bigbone-rx/src/main/kotlin/social/bigbone/rx/RxTimelineMethods.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/AccountMethods.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/MarkerMethods.kt
Labels: documentation

#379 lists: Add “exclusive” parameter for full support
  bigbone-rx/src/main/kotlin/social/bigbone/rx/RxListMethods.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/ListMethods.kt
  docs/api-coverage/lists.md
Labels: documentation, enhancement

#390 Mock server testing instead of hitting actual website
  bigbone/src/test/kotlin/social/bigbone/MastodonClientTest.kt
Labels: bug, pipeline

#382 Update scopes used in OAuth
  USAGE.md
  bigbone-rx/src/main/kotlin/social/bigbone/rx/RxAppMethods.kt
  bigbone-rx/src/main/kotlin/social/bigbone/rx/RxOAuthMethods.kt
  bigbone/src/integrationTest/kotlin/social/bigbone/TestConstants.kt
  bigbone/src/integrationTest/kotlin/social/bigbone/TestHelpers.kt
  bigbone/src/integrationTest/kotlin/social/bigbone/v300/V300StatusMethodsIntegrationTest.kt
  bigbone/src/integrationTest/kotlin/social/bigbone/v402/V402StatusMethodsIntegrationTest.kt
  bigbone/src/main/kotlin/social/bigbone/api/Scope.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/AppMethods.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/OAuthMethods.kt
  bigbone/src/test/assets/access_token.json
  bigbone/src/test/kotlin/social/bigbone/api/entity/TokenTest.kt
  bigbone/src/test/kotlin/social/bigbone/api/method/AppMethodsTest.kt
  bigbone/src/test/kotlin/social/bigbone/api/method/OAuthMethodsTest.kt
  bigbone/src/test/kotlin/social/bigbone/entity/ScopeTest.kt
  sample-java/src/main/java/social/bigbone/sample/Authenticator.java
  sample-java/src/main/java/social/bigbone/sample/GetAppRegistration.java
  sample-java/src/main/java/social/bigbone/sample/OAuthGetAccessToken.java
  sample-kotlin/src/main/kotlin/social/bigbone/sample/Authenticator.kt
  sample-kotlin/src/main/kotlin/social/bigbone/sample/OAuthGetAccessToken.kt
Labels: enhancement, breaking

#383 Rewrite streaming API to use websocket
  USAGE.md
  bigbone-rx/src/main/kotlin/social/bigbone/rx/RxStreamingMethods.kt
  bigbone-rx/src/test/kotlin/social/bigbone/rx/RxStreamingMethodsTest.kt
  bigbone-rx/src/test/kotlin/social/bigbone/rx/testtool/MockClient.kt
  bigbone/src/main/kotlin/social/bigbone/MastodonClient.kt
  bigbone/src/main/kotlin/social/bigbone/api/Dispatcher.kt
  bigbone/src/main/kotlin/social/bigbone/api/Handler.kt
  bigbone/src/main/kotlin/social/bigbone/api/Shutdownable.kt
  bigbone/src/main/kotlin/social/bigbone/api/entity/Reaction.kt
  bigbone/src/main/kotlin/social/bigbone/api/entity/streaming/ParsedStreamEvent.kt
  bigbone/src/main/kotlin/social/bigbone/api/entity/streaming/RawStreamEvent.kt
  bigbone/src/main/kotlin/social/bigbone/api/entity/streaming/StreamType.kt
  bigbone/src/main/kotlin/social/bigbone/api/entity/streaming/StreamingAnnouncementReaction.kt
  bigbone/src/main/kotlin/social/bigbone/api/entity/streaming/WebSocketCallback.kt
  bigbone/src/main/kotlin/social/bigbone/api/entity/streaming/WebSocketEvent.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/StreamingMethods.kt
  bigbone/src/test/kotlin/social/bigbone/api/method/StreamingMethodsTest.kt
  bigbone/src/test/kotlin/social/bigbone/testtool/MockClient.kt
  bigbone/src/test/kotlin/social/bigbone/testtool/TestUtil.kt
  docs/api-coverage/streaming.md
  sample-java/src/main/java/social/bigbone/sample/Authenticator.java
  sample-java/src/main/java/social/bigbone/sample/StreamFederatedPublicTimeline.java
  sample-kotlin/src/main/kotlin/social/bigbone/sample/Authenticator.kt
  sample-kotlin/src/main/kotlin/social/bigbone/sample/RxStreamPublicTimeline.kt
  sample-kotlin/src/main/kotlin/social/bigbone/sample/StreamFederatedPublicTimeline.kt
Labels: documentation, enhancement, breaking

#392 Add ip block admin-related methods
  bigbone-rx/src/main/kotlin/social/bigbone/rx/admin/RxAdminIpBlockMethods.kt
  bigbone/src/main/kotlin/social/bigbone/MastodonClient.kt
  bigbone/src/main/kotlin/social/bigbone/api/entity/admin/AdminIpBlock.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/admin/AdminIpBlockMethods.kt
  bigbone/src/test/assets/admin_ip_blocks_get_all.json
  bigbone/src/test/assets/admin_ip_blocks_single.json
  bigbone/src/test/kotlin/social/bigbone/api/method/admin/AdminIpBlockMethodsTest.kt
  docs/api-coverage/admin/ip-blocks.md
Labels: documentation, enhancement

#402 Fix broken Admin::IpBlocks kDoc links
  bigbone-rx/src/main/kotlin/social/bigbone/rx/admin/RxAdminIpBlockMethods.kt
  bigbone/src/main/kotlin/social/bigbone/MastodonClient.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/admin/AdminIpBlockMethods.kt
Labels: documentation

#397 Add Admin::DomainBlocks entity and methods
  bigbone-rx/src/main/kotlin/social/bigbone/rx/admin/RxAdminDomainBlockMethods.kt
  bigbone/src/main/kotlin/social/bigbone/MastodonClient.kt
  bigbone/src/main/kotlin/social/bigbone/api/entity/admin/AdminDomainBlock.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/admin/AdminDomainBlockMethods.kt
  bigbone/src/test/assets/admin_domain_blocks_block_success.json
  bigbone/src/test/assets/admin_domain_blocks_delete_success.json
  bigbone/src/test/assets/admin_domain_blocks_get_all_success.json
  bigbone/src/test/assets/admin_domain_blocks_get_single_success.json
  bigbone/src/test/assets/admin_domain_blocks_update_success.json
  bigbone/src/test/kotlin/social/bigbone/api/method/admin/AdminDomainBlockMethodsTest.kt
  docs/api-coverage/admin/domain-blocks.md
Labels: documentation, enhancement

#400 Add Admin::EmailDomainBlock methods
  bigbone-rx/src/main/kotlin/social/bigbone/rx/admin/RxAdminEmailDomainBlockMethods.kt
  bigbone/src/main/kotlin/social/bigbone/MastodonClient.kt
  bigbone/src/main/kotlin/social/bigbone/api/entity/admin/AdminEmailDomainBlock.kt
  bigbone/src/main/kotlin/social/bigbone/api/entity/data/History.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/admin/AdminEmailDomainBlockMethods.kt
  bigbone/src/test/assets/admin_email_domain_blocks_all_blocked_success.json
  bigbone/src/test/assets/admin_email_domain_blocks_block_success.json
  bigbone/src/test/assets/admin_email_domain_blocks_delete_success.json
  bigbone/src/test/assets/admin_email_domain_blocks_single_success.json
  bigbone/src/test/kotlin/social/bigbone/api/method/admin/AdminEmailDomainBlockMethodsTest.kt
  docs/api-coverage/admin/email-domain-blocks.md
Labels: documentation, enhancement

#403 Add Admin::CanonicalEmailBlocks methods
  bigbone-rx/src/main/kotlin/social/bigbone/rx/admin/RxAdminCanonicalEmailBlockMethods.kt
  bigbone/src/main/kotlin/social/bigbone/MastodonClient.kt
  bigbone/src/main/kotlin/social/bigbone/api/entity/admin/AdminCanonicalEmailBlock.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/admin/AdminCanonicalEmailBlockMethods.kt
  bigbone/src/test/assets/admin_canonical_email_blocks_all_blocked_success.json
  bigbone/src/test/assets/admin_canonical_email_blocks_block_success.json
  bigbone/src/test/assets/admin_canonical_email_blocks_delete_success.json
  bigbone/src/test/assets/admin_canonical_email_blocks_single_success.json
  bigbone/src/test/assets/admin_canonical_email_blocks_test_success.json
  bigbone/src/test/kotlin/social/bigbone/api/method/admin/AdminCanonicalEmailBlockMethodsTest.kt
  docs/api-coverage/admin/canonical-email-blocks.md
Labels: documentation, enhancement

#404 Add Admin::Accounts methods
  bigbone-rx/src/main/kotlin/social/bigbone/rx/admin/RxAdminAccountMethods.kt
  bigbone/src/main/kotlin/social/bigbone/MastodonClient.kt
  bigbone/src/main/kotlin/social/bigbone/api/Range.kt
  bigbone/src/main/kotlin/social/bigbone/api/entity/Role.kt
  bigbone/src/main/kotlin/social/bigbone/api/entity/admin/AccountOrigin.kt
  bigbone/src/main/kotlin/social/bigbone/api/entity/admin/AccountStatus.kt
  bigbone/src/main/kotlin/social/bigbone/api/entity/admin/ActionAgainstAccount.kt
  bigbone/src/main/kotlin/social/bigbone/api/entity/admin/AdminAccount.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/admin/AdminAccountMethods.kt
  bigbone/src/test/assets/admin_accounts_approve_success.json
  bigbone/src/test/assets/admin_accounts_delete_success.json
  bigbone/src/test/assets/admin_accounts_enable_disabled_success.json
  bigbone/src/test/assets/admin_accounts_reject_success.json
  bigbone/src/test/assets/admin_accounts_unsensitive_success.json
  bigbone/src/test/assets/admin_accounts_unsilence_success.json
  bigbone/src/test/assets/admin_accounts_unsuspend_success.json
  bigbone/src/test/assets/admin_accounts_view_account_success.json
  bigbone/src/test/assets/admin_accounts_view_accounts_success.json
  bigbone/src/test/assets/admin_accounts_view_posts_success.json
  bigbone/src/test/kotlin/social/bigbone/api/entity/RoleTest.kt
  bigbone/src/test/kotlin/social/bigbone/api/method/admin/AdminAccountMethodsTest.kt
  docs/api-coverage/admin/accounts.md
Labels: documentation, enhancement

#413 Add Admin::DomainAllow methods
  bigbone-rx/src/main/kotlin/social/bigbone/rx/admin/RxAdminDomainAllowMethods.kt
  bigbone/src/main/kotlin/social/bigbone/MastodonClient.kt
  bigbone/src/main/kotlin/social/bigbone/api/entity/admin/AdminDomainAllow.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/admin/AdminDomainAllowMethods.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/admin/AdminDomainBlockMethods.kt
  bigbone/src/test/assets/admin_domain_allow.json
  bigbone/src/test/assets/admin_domain_allow_list.json
  bigbone/src/test/kotlin/social/bigbone/api/method/admin/AdminDomainAllowMethodsTest.kt
  docs/api-coverage/admin/domain-allows.md
Labels: enhancement

#399 Add Admin::Trends methods
  bigbone-rx/src/main/kotlin/social/bigbone/rx/admin/RxAdminTrendMethods.kt
  bigbone/src/main/kotlin/social/bigbone/MastodonClient.kt
  bigbone/src/main/kotlin/social/bigbone/api/entity/admin/AdminTag.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/admin/AdminTrendMethods.kt
  bigbone/src/test/assets/admin_trends_trending_links_success.json
  bigbone/src/test/assets/admin_trends_trending_statuses_success.json
  bigbone/src/test/assets/admin_trends_trending_tags_success.json
  bigbone/src/test/kotlin/social/bigbone/api/method/admin/AdminTrendMethodsTest.kt
  docs/api-coverage/admin/trends.md
Labels: documentation, enhancement

#410 Clean up endpoint definitions in methods classes
  bigbone/src/main/kotlin/social/bigbone/api/method/AccountMethods.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/AnnouncementMethods.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/AppMethods.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/BlockMethods.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/BookmarkMethods.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/ConversationMethods.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/CustomEmojiMethods.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/DirectoryMethods.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/DomainBlockMethods.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/EmailMethods.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/EndorsementMethods.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/FavouriteMethods.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/FeaturedTagMethods.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/FilterMethods.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/FollowRequestMethods.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/FollowedTagMethods.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/InstanceMethods.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/ListMethods.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/MarkerMethods.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/MuteMethods.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/NotificationMethods.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/OAuthMethods.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/OEmbedMethods.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/PollMethods.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/PreferenceMethods.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/PushNotificationMethods.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/ReportMethods.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/SearchMethods.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/StatusMethods.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/StreamingMethods.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/SuggestionMethods.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/TagMethods.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/TimelineMethods.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/TrendMethods.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/admin/AdminAccountMethods.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/admin/AdminCanonicalEmailBlockMethods.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/admin/AdminDimensionMethods.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/admin/AdminEmailDomainBlockMethods.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/admin/AdminIpBlockMethods.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/admin/AdminMeasureMethods.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/admin/AdminRetentionMethods.kt
  bigbone/src/test/kotlin/social/bigbone/api/method/DomainBlockMethodsTest.kt
  bigbone/src/test/kotlin/social/bigbone/api/method/InstanceMethodsTest.kt
  bigbone/src/test/kotlin/social/bigbone/api/method/admin/AdminIpBlockMethodsTest.kt
Labels: code quality
