Repository PattaFeuFeu/bigbone, pull requests merged in 2025-04, with the labels that each got.

#563 Limit PR builds to specific types; cancel on new push
  .github/workflows/build.yml
Labels: pipeline

#557 Add Filter.FilterAction.BLUR
  bigbone/src/main/kotlin/social/bigbone/api/entity/Filter.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/FilterMethods.kt
  bigbone/src/test/assets/filter_unknown_action.json
  bigbone/src/test/kotlin/social/bigbone/api/entity/FilterTest.kt
  sample-java/src/main/java/social/bigbone/sample/GetHomeTimelineWithFiltering.java
  sample-kotlin/src/main/kotlin/social/bigbone/sample/GetHomeTimelineWithFiltering.kt
Labels: enhancement

#573 Add new user age restrictions
  bigbone-rx/src/main/kotlin/social/bigbone/rx/RxAccountMethods.kt
  bigbone/src/main/kotlin/social/bigbone/api/entity/Instance.kt
  bigbone/src/main/kotlin/social/bigbone/api/method/AccountMethods.kt
  bigbone/src/test/assets/instance_extended.json
  bigbone/src/test/kotlin/social/bigbone/api/method/AccountMethodsTest.kt
  bigbone/src/test/kotlin/social/bigbone/api/method/InstanceMethodsTest.kt
Labels: enhancement, breaking
